### ISSUE TITLE
👀  Integrate Microsoft Doc Intelligence for OCR

### ISSUE THREAD

**Issue by asim-shrestha** [reworkd/tarsier#71]
Currently the only OCR service Tarsier supports is GoogleOCR vision. We're told Microsoft's model is the most performant so would love to also include it!

Documentation: https://learn.microsoft.com/en-us/azure/ai-services/document-intelligence/concept-read?view=doc-intel-4.0.0

**Comment by ml5ah** [comment]
Document Intelligence has more advanced capabilities for processing multi-page documents. Since for tarsier, we're dealing with screenshots (single images), it's easier to integrate their OCR service as a start. 
Please see https://github.com/reworkd/tarsier/issues/84 and https://github.com/reworkd/tarsier/pull/85

@asim-shrestha @awtkns

**Comment by awtkns** [comment]
That sounds great @ml5ah !
